language: node_js
node_js:
- '12'
- '10'
script: npm run ci
cache:
  directories:
  - "~/.npm"

x-deploy: &deploy
  edge: true
  provider: npm
  email: njirem@gmail.com
  access: public
  api_key:
    secure: DlLcLI5m0X6d9qXkWvhr9HCcT+pQTGhm6VHRM7Tfd9q2uDi/shkkM6hG/nA+iK5r2cz1mZtwVKk4Zx2eByXROOOTzaNmbx475Yh2Z5AANepNzk8uz7tB1RAR+A1U9AMFqCDDVmzL++kXypp6sLPpbJT/NIiMS3UpBlDC52adLnq/HmudRdTaPpdKL/wuxIhVFf3ROvQEXIJCwqnjfz3+SSLp7KQngJsEenI58o8vvQ5Ry347HDQV1ROU3tUbNMp71RVKmcIxi39khtBvO4uwDGhdJkxptykDX2vGyqs2huWc2cZDevCPOsRDIqg+xYXqRHrHwoeHhUC4eyxJg3lIBxdLFSZlr5kXM1hNO/z0FLQkicuFoU5t2J9pojWt4HZPJSNxNS9mRwnsB4TE9nHmaJE9PgBYuP5DMMoW5cF6X27GA3AyEC2F/IKznPTbn1gv4il+y7GAsjNhGnjH/02JwzuzxTMw6fc3pdZIpNwOwMyb2Xzx/cPmG5xk34t6Xw/TwH4va/z1sv4KKBYaYSOeUjH59d1HvQOW97fGrCp+qXeM5zXAnQqVGxIh+RIVttAmp7ftFYi1dRcr4fI9eTnwzbTGypzws2t5+JspTi2USxgJHelndJO+14bC4UpLqBsLkbjD/nZ64E8TsFyEqCGMgA5ClBcKdLBk/tQixz4Avf8=
  on:
    branch: master
    node: 10
deploy:
- <<: *deploy
  src: dist/sherfire
- <<: *deploy
  src: dist/ng-sherfire
