language: node_js
node_js:
- '12'
- '10'
script: npm run ci
cache:
  directories:
  - "~/.npm"

x-deploy: &deploy
  edge: true
  provider: npm
  email: njirem@gmail.com
  api_token:
    secret: AEK3xzjOGiu8rP/1MhQ19Z1hYPMZyDiQZWovvDacgXOG5etjo1qGzN3QFM+KJAy9B645ObUbtOQa7aCarQiZUThH+AIqb75u3J9NKr/xh80lA80bbiu0plmFerxbzfm4WkSriSga51HRauA3SDAZ91iXCPGwtsumORnwNxU6BM3o2rGG0HEtIOogmK4/TdQDcTliAAHKXfrwvjCt9SlXMLb4t97bQ4QN0Dw5Bv2GJZKuKEmLbV/hFvgw1H00tyEXyqh8nPWbSRs+Z1wfp1EjzatPSOaW5rMncS665Z5e/fKIj9B+yDptYl5gM8CwFQoCJvn24ticbjmeAFhhm3SjdGA6v8tC/UHDo1Do8GBLYVA7a6FVjfYOl4PHhsv6Z4R4V85B7SOmo/3E9QBHKal+sIX2Wx2lXFpvOw72QAlzzxv4W7VskqTq+sghwGqWS1uAJb8wheBnUwQbw5pMKKYDokOd7PnpXu5J1akh2rXpdZc5UH0lbDhAGvespQU2l3QF4UECAp+REcdfMBnS/02LbX6ao5kow3YNrY+EPJw2poRUSQOP+5Z9K12F15u6NPpL7I4faICpXr9FOgwStyJb9zNEqQDURp2HCbo6RFEAcOyVNDmRNMTCIk+OpqENm3bSH8iJ2e/MWV0A+tWXMGiUYolMux1UuBT/joSnKfj+DfA=
  on:
    branch: master
    node: 10
deploy:
- <<: *deploy
  src: dist/sherfire
- <<: *deploy
  src: dist/ng-sherfire

env:
  global:
  # NPM_TOKEN
  - secure: ggJgqhx7ehaCVFTL9/qSS3xCy+S73QVYPNO3jwUblceUddVEyflhAJAX2Qg8qGPCl6qsHrPNvXlN09OCeVA6nwwOb3mULz9aqNWHWmJE++KzosVR/rAXvxp6+3Oy+96x3A8cahK7I0o6+t6L9En7zlalrXK+djQcYSVn6xb+kSxu1XlAv9i8QG7xs9f7JhWn4LbgAq0Ztk1qIqiEHfSoA3LB4d+XpswF4VRg0ALTJ4wxIHqP2BZo6uPvyeaqNVIZvn3G7Rv/9PBrORQOHYza4eLC6VG5jzl3cb1GfJu5cEdgK51rHgE8QFn+Sn783ZAjwwNena3NZK6xnYcgP+5tRvRV4vPP3PZkCDp85QU5iANACyZkatsFGnhzg0ATrKH0hAf/gv4+2nhRyQPl8gey5xSuXzuxmg2OeVQpc193fJl5WPV0XR9u8f/6Nt/tmegcP4UDS1sPanxRfAjlDUtaZWkfxo/tP+O7aQgrZ/iL4u+LSv1rrJFA5FTX/ql8jcOv1SPWJ17/eYG8rUSwLuxAuDCRCyCn0uAVa8gJ45aKaMOG2NKyeTBjp1QA0Hr/0lhMot8kaptBJZ2/krZMcQeJfXy8ft9BJBNgmUlMBT9+WrlXxIeYrh71yvIjV1hHcUgRFkKcXipatlPw/jglqEflaTvfAyWmrSSoqdLHLbzrvMM=
