language: node_js
node_js:
- '12'
- '10'
script: npm run ci
cache:
  directories:
  - "~/.npm"

x-deploy: &deploy
  edge: true
  provider: npm
  email: njirem@gmail.com
  on:
    branch: master
    node: 10
deploy:
- <<: *deploy
  src: dist/sherfire
- <<: *deploy
  src: dist/ng-sherfire

env:
  global:
    - secure: ggJgqhx7ehaCVFTL9/qSS3xCy+S73QVYPNO3jwUblceUddVEyflhAJAX2Qg8qGPCl6qsHrPNvXlN09OCeVA6nwwOb3mULz9aqNWHWmJE++KzosVR/rAXvxp6+3Oy+96x3A8cahK7I0o6+t6L9En7zlalrXK+djQcYSVn6xb+kSxu1XlAv9i8QG7xs9f7JhWn4LbgAq0Ztk1qIqiEHfSoA3LB4d+XpswF4VRg0ALTJ4wxIHqP2BZo6uPvyeaqNVIZvn3G7Rv/9PBrORQOHYza4eLC6VG5jzl3cb1GfJu5cEdgK51rHgE8QFn+Sn783ZAjwwNena3NZK6xnYcgP+5tRvRV4vPP3PZkCDp85QU5iANACyZkatsFGnhzg0ATrKH0hAf/gv4+2nhRyQPl8gey5xSuXzuxmg2OeVQpc193fJl5WPV0XR9u8f/6Nt/tmegcP4UDS1sPanxRfAjlDUtaZWkfxo/tP+O7aQgrZ/iL4u+LSv1rrJFA5FTX/ql8jcOv1SPWJ17/eYG8rUSwLuxAuDCRCyCn0uAVa8gJ45aKaMOG2NKyeTBjp1QA0Hr/0lhMot8kaptBJZ2/krZMcQeJfXy8ft9BJBNgmUlMBT9+WrlXxIeYrh71yvIjV1hHcUgRFkKcXipatlPw/jglqEflaTvfAyWmrSSoqdLHLbzrvMM=
