language: node_js
node_js:
- '12'
- '10'
script: npm run ci
cache: npm

x-deploy: &deploy
  edge: true
  provider: npm
  email: njirem@gmail.com
  on:
    branch: master
    node: 10
deploy:
- <<: *deploy
  src: dist/sherfire
- <<: *deploy
  src: dist/ng-sherfire
